# Generated by Django 3.2.7 on 2024-05-06 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='available_slots',
            field=models.ManyToManyField(blank=True, null=True, to='api.TimeSlot'),
        ),
    ]
